//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartLibrary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartLibrary.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied. Please contact the administrator..
        /// </summary>
        public static string AccessDeniedMessage {
            get {
                return ResourceManager.GetString("AccessDeniedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book has been added to Favourite.
        /// </summary>
        public static string AddBookInterest {
            get {
                return ResourceManager.GetString("AddBookInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your comment has added..
        /// </summary>
        public static string AddComment {
            get {
                return ResourceManager.GetString("AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill all password details to change your password.
        /// </summary>
        public static string AllPasswordRequired {
            get {
                return ResourceManager.GetString("AllPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This book is already Borrowed..
        /// </summary>
        public static string AlreadyBookBorrowed {
            get {
                return ResourceManager.GetString("AlreadyBookBorrowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This book is already borrowed for this member..
        /// </summary>
        public static string AlreadyBookBorrowedforCustomer {
            get {
                return ResourceManager.GetString("AlreadyBookBorrowedforCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This book is already pending for this member..
        /// </summary>
        public static string AlreadyBookIsPending {
            get {
                return ResourceManager.GetString("AlreadyBookIsPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrowed Book is Successfully {0}..
        /// </summary>
        public static string ApproveRejectBorrowedBook {
            get {
                return ResourceManager.GetString("ApproveRejectBorrowedBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space Booking has been {0}..
        /// </summary>
        public static string ApproveSpaceBookingStatus {
            get {
                return ResourceManager.GetString("ApproveSpaceBookingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not add Blank Comment.
        /// </summary>
        public static string BlankComment {
            get {
                return ResourceManager.GetString("BlankComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected booking area is unavailable for selected time..
        /// </summary>
        public static string BookingAreaUnavailable {
            get {
                return ResourceManager.GetString("BookingAreaUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking area is unavailable..
        /// </summary>
        public static string BookingAreaUnavailableTooltip {
            get {
                return ResourceManager.GetString("BookingAreaUnavailableTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book&apos;s current quantity can not be less than  zero..
        /// </summary>
        public static string BookInvalidCurrentQuantity {
            get {
                return ResourceManager.GetString("BookInvalidCurrentQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, Book is not available..
        /// </summary>
        public static string BookNotAvailable {
            get {
                return ResourceManager.GetString("BookNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is period for which you want to borrow the book..
        /// </summary>
        public static string BookPeriodMessage {
            get {
                return ResourceManager.GetString("BookPeriodMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in returning book..
        /// </summary>
        public static string BookReturnError {
            get {
                return ResourceManager.GetString("BookReturnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book is return successfully..
        /// </summary>
        public static string BookReturnSuccess {
            get {
                return ResourceManager.GetString("BookReturnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Status.
        /// </summary>
        public static string BookStatus {
            get {
                return ResourceManager.GetString("BookStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your book is borrowed successfully. Waiting for administrator Approval..
        /// </summary>
        public static string BorrowBookAdd {
            get {
                return ResourceManager.GetString("BorrowBookAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This book is borrowed on behalf of this member..
        /// </summary>
        public static string BorrowBookAddforCustomer {
            get {
                return ResourceManager.GetString("BorrowBookAddforCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in Borrowing Book..
        /// </summary>
        public static string BorrowBookError {
            get {
                return ResourceManager.GetString("BorrowBookError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can request for the book on behalf of member which he/she  want to borrow..
        /// </summary>
        public static string BorrowBookforCustomerHeader {
            get {
                return ResourceManager.GetString("BorrowBookforCustomerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can request for the book which you want to borrow..
        /// </summary>
        public static string BorrowBookHeader {
            get {
                return ResourceManager.GetString("BorrowBookHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in changing password..
        /// </summary>
        public static string ChangePasswordError {
            get {
                return ResourceManager.GetString("ChangePasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Quantity  can not be more than Total Quantity ..
        /// </summary>
        public static string CurrentQtyCannotbeMoreThanTotalQuantity {
            get {
                return ResourceManager.GetString("CurrentQtyCannotbeMoreThanTotalQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already in use. You cannot delete this {0}..
        /// </summary>
        public static string DeleteErrorMessage {
            get {
                return ResourceManager.GetString("DeleteErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been deleted successfully..
        /// </summary>
        public static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate {0} is not allowed..
        /// </summary>
        public static string DuplicateMessage {
            get {
                return ResourceManager.GetString("DuplicateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not exist in Active Directory,Please Contact Administrator.
        /// </summary>
        public static string EmailNotExistInAD {
            get {
                return ResourceManager.GetString("EmailNotExistInAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Email Addresss.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email successfully Sent.
        /// </summary>
        public static string EmailSent {
            get {
                return ResourceManager.GetString("EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Sent Failed..
        /// </summary>
        public static string EmailSentFailed {
            get {
                return ResourceManager.GetString("EmailSentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in {0} Borrowed Book..
        /// </summary>
        public static string ErrorApproveRejectBorrowedBook {
            get {
                return ResourceManager.GetString("ErrorApproveRejectBorrowedBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Content cannot be null or empty..
        /// </summary>
        public static string FileContentNull {
            get {
                return ResourceManager.GetString("FileContentNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size exceeds the maximum size allowed..
        /// </summary>
        public static string FileSizeClient {
            get {
                return ResourceManager.GetString("FileSizeClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size can&apos;t be more than {0} MB..
        /// </summary>
        public static string FileSizeError {
            get {
                return ResourceManager.GetString("FileSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file type of the attempted upload is invalid..
        /// </summary>
        public static string FileTypeClient {
            get {
                return ResourceManager.GetString("FileTypeClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} books are borrowed. {1} must be more than or equal to {0}..
        /// </summary>
        public static string InvalidBookTotalQuantityMessage {
            get {
                return ResourceManager.GetString("InvalidBookTotalQuantityMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not valid..
        /// </summary>
        public static string InvalidFieldMessage {
            get {
                return ResourceManager.GetString("InvalidFieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file extension..
        /// </summary>
        public static string InValidFileExtension {
            get {
                return ResourceManager.GetString("InValidFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select valid image..
        /// </summary>
        public static string InvalidImageMessage {
            get {
                return ResourceManager.GetString("InvalidImageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Not Valid.
        /// </summary>
        public static string InvalidInputMessage {
            get {
                return ResourceManager.GetString("InvalidInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ISBN..
        /// </summary>
        public static string InvalidISBNMessage {
            get {
                return ResourceManager.GetString("InvalidISBNMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Phone Number.
        /// </summary>
        public static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} value must be between {1} and {2}..
        /// </summary>
        public static string InvalidRangeMessage {
            get {
                return ResourceManager.GetString("InvalidRangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL is not valid..
        /// </summary>
        public static string InvalidUrlMessage {
            get {
                return ResourceManager.GetString("InvalidUrlMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Detail Fetch Successfully..
        /// </summary>
        public static string ISBNFetchSuccess {
            get {
                return ResourceManager.GetString("ISBNFetchSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member is already register to the site.
        /// </summary>
        public static string MemberAlreadyRegistered {
            get {
                return ResourceManager.GetString("MemberAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no books in your favourite list.
        /// </summary>
        public static string NoBooksinFavourite {
            get {
                return ResourceManager.GetString("NoBooksinFavourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Borrowed Books.
        /// </summary>
        public static string NoBorrowedBooks {
            get {
                return ResourceManager.GetString("NoBorrowedBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No delayed books..
        /// </summary>
        public static string NoDelayed {
            get {
                return ResourceManager.GetString("NoDelayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No event requests..
        /// </summary>
        public static string NoEventRequests {
            get {
                return ResourceManager.GetString("NoEventRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already in use so you cannot Inactive this..
        /// </summary>
        public static string NoInactiveMessage {
            get {
                return ResourceManager.GetString("NoInactiveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already in use so you cannot Inactive this..
        /// </summary>
        public static string NoInactiveMessage1 {
            get {
                return ResourceManager.GetString("NoInactiveMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No message..
        /// </summary>
        public static string NoMessage {
            get {
                return ResourceManager.GetString("NoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No notifications..
        /// </summary>
        public static string NoNotifications {
            get {
                return ResourceManager.GetString("NoNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking area capacity is {0}. {1} must be less than or equal to {0}..
        /// </summary>
        public static string NoOfAttendeeExceedCapacity {
            get {
                return ResourceManager.GetString("NoOfAttendeeExceedCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Record Found.
        /// </summary>
        public static string NoRecordFound {
            get {
                return ResourceManager.GetString("NoRecordFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No books to return for today..
        /// </summary>
        public static string NoReturnToday {
            get {
                return ResourceManager.GetString("NoReturnToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Rooms Booked.
        /// </summary>
        public static string NoRoomsBooked {
            get {
                return ResourceManager.GetString("NoRoomsBooked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to access this page.&lt;br&gt; If you require to access this page, Please contact system administrator..
        /// </summary>
        public static string NotAuthorizedMeesage {
            get {
                return ResourceManager.GetString("NotAuthorizedMeesage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification will be sent to you once book is available.
        /// </summary>
        public static string NotifyMeMessage {
            get {
                return ResourceManager.GetString("NotifyMeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Users Found.
        /// </summary>
        public static string NoUsersFound {
            get {
                return ResourceManager.GetString("NoUsersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Failed.
        /// </summary>
        public static string PasswordEmailSendFail {
            get {
                return ResourceManager.GetString("PasswordEmailSendFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password length must be between {2} and {1}.
        /// </summary>
        public static string PasswordLengthMessageMinMax {
            get {
                return ResourceManager.GetString("PasswordLengthMessageMinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity must be numeric..
        /// </summary>
        public static string QuantityMustBeNumeric {
            get {
                return ResourceManager.GetString("QuantityMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book has been removed from Favourite.
        /// </summary>
        public static string RemoveBookInterest {
            get {
                return ResourceManager.GetString("RemoveBookInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Cover Image is required..
        /// </summary>
        public static string RequiredBookCoverImage {
            get {
                return ResourceManager.GetString("RequiredBookCoverImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        public static string RequiredFieldMessage {
            get {
                return ResourceManager.GetString("RequiredFieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal characters in string!.
        /// </summary>
        public static string RestrictIllegalCharacters {
            get {
                return ResourceManager.GetString("RestrictIllegalCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} saved successfully..
        /// </summary>
        public static string SaveMessage {
            get {
                return ResourceManager.GetString("SaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select user to send message.
        /// </summary>
        public static string SelectUserToSendMessage {
            get {
                return ResourceManager.GetString("SelectUserToSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in sending the message..
        /// </summary>
        public static string SendMessageError {
            get {
                return ResourceManager.GetString("SendMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message sent successfully..
        /// </summary>
        public static string SendMessageSuccess {
            get {
                return ResourceManager.GetString("SendMessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has been expired, You will redirect to login page..
        /// </summary>
        public static string SessionExpiredMessage {
            get {
                return ResourceManager.GetString("SessionExpiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please contact system administrator..
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space Booking has been Rescheduled..
        /// </summary>
        public static string SpaceBookingReschedule {
            get {
                return ResourceManager.GetString("SpaceBookingReschedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space booking period must be in future..
        /// </summary>
        public static string SpaceBookingTimeMessage {
            get {
                return ResourceManager.GetString("SpaceBookingTimeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length should be {1}.
        /// </summary>
        public static string StringLengthMessage {
            get {
                return ResourceManager.GetString("StringLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your operation is successfully done..
        /// </summary>
        public static string SuccessMessage {
            get {
                return ResourceManager.GetString("SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than {1}..
        /// </summary>
        public static string TimeCompareMessage {
            get {
                return ResourceManager.GetString("TimeCompareMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} updated successfully..
        /// </summary>
        public static string UpdateMessage {
            get {
                return ResourceManager.GetString("UpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL is no longer valid..
        /// </summary>
        public static string UrlExpiredMessage {
            get {
                return ResourceManager.GetString("UrlExpiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t find an account matching the user account you entered. Please check your detail and try again..
        /// </summary>
        public static string UserAccountNotmatched {
            get {
                return ResourceManager.GetString("UserAccountNotmatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name must have a value and an extension..
        /// </summary>
        public static string ValidValueandExtension {
            get {
                return ResourceManager.GetString("ValidValueandExtension", resourceCulture);
            }
        }
    }
}
